---
- name: Include debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Inclued driver.yml
  ansible.builtin.include_tasks: driver.yml
