---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      OS_AUTH_TYPE: v3applicationcredential
      OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
      OS_IDENTITY_API_VERSION: 3
      OS_REGION_NAME: SDSC
      OS_INTERFACE: public
      OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
      OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
      MOLECULE_DRIVER_DOWNLOAD_URL: ${{ secrets.MOLECULE_DRIVER_DOWNLOAD_URL }}
      MOLECULE_LICENSE_SERVER_ADDRESS: ${{ secrets.MOLECULE_LICENSE_SERVER_ADDRESS }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint molecule molecule-openstack netaddr openstacksdk==0.61 python-openstackclient --force-reinstall
          ansible --version
          ansible-lint --version
          molecule --version
      - name: Test with molecule on Ubuntu 22.04
        run: |
          molecule test --all
        env:
          MOLECULE_IMAGE: "Ubuntu 22.04 LTS x86_64"
          MOLECULE_SSH_USER: ubuntu
      - name: Test with molecule on RHEL 8
        run: |
          molecule test --all
        env:
          MOLECULE_IMAGE: "AlmaLinux 8.5 x86_64"
          MOLECULE_SSH_USER: almalinux
